config/routes.rb
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
  
     post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
     post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information

     post "/shipments/add_admin_shipment_details" => "shipments#add_admin_shipment_details", as: :add_admin_shipment_details
  
     get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

     resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :primary_vehicle

    resources :pages
    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
    end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :preferred_location , except: [:destroy]
    resources :vehicle_types, except: [:destroy]

    resources :blogs, except: [:destroy]
    resources :locations
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]

    resources :change_destination_requests
    resources :vendor, except: [:destroy]
    resources :shipments do
      collection do
      get :cargo_invoice
      put :presign_upload

      end
      member do
        delete :cancel
        get :assign_vehicle
        get :assign_cost
        get :email
        get :edit_history

        patch :status_email





      end
      collection do
        post :get_bulk_coordinates

      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
      collection do
        post :get_all_drivers
        post :get_all_drivers_filtered
        get :change_password


      end
    end


    resources :payments
  end

  namespace :moderator do
    root 'dashboard#index'
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing

    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
    post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
    post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

    resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :vendor, except: [:destroy]
      resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
      end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]
    resources :dashboard , only: [:index]
    resources :preferred_location , except: [:destroy]

    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :payments
    resources :shipments do
      collection do
        get :cargo_invoice
        put :presign_upload

        end

      member do
        delete :cancel
        get :assign_vehicle
        get :assign_cost
         get :email
         patch :status_email
         get :edit_history
      end
      
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
      collection do
        post :get_all_drivers
        post :get_all_drivers_filtered

      end
    end


   end

  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
        post :get_bulk_filtered_coordinates

        get :pickup_location
        get :dropoff_location
        get :vehicle_type
        get :image_select
        get :eta_update
        get :update_timer
        get :no_bids
        get :no_selected
        get :update_bids
        get :update_upcoming
     

      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
        
      end

    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index] do 
      collection do
      get :filtered_dashboard
      end
    end
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
     
    end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end

app/controllers/moderator/cargo_company_controller.rb
class Moderator::CargoCompanyController < ModeratorController
  layout 'moderator'

  include UserConcern
  before_action :set_user , only: [:show]
  before_action :set_users_link  , only: [:index , :show]
  before_action :check_if_moderator, only: [:new , :create]

  def index
    @users = User.all.reverse
  end


  def new
    @admin_cargo  = User.new
  end

  def create
    country_id = params[:user][:country_id]
    initial_mobile_number = params[:user][:mobile]
    params[:user][:mobile] = make_phone_number country_id , params[:user][:mobile]
    phone_number_valid = phone_number_valid?( country_id,  params[:user][:mobile] )

    params[:user][:password] ="12345678"
    @admin_cargo = User.new(admin_cargo_params)
    @admin_cargo.role = :cargo_owner
    
    if phone_number_valid and @admin_cargo.save
    @admin_cargo.register_as_company
      @admin_cargo.update(mobile_verified: "verified", verification_code: "",terms_accepted: TRUE)
      get_company_information
      # UserMailer.send_admin_credentials_to_super_admin(current_user.email, @admin_user.id , @password).deliver
    
    else !phone_number_valid
      flash[:error] = "Invalid Phone number." 
       render :new
      end
    

  end
  def get_company_information

    @current_cargo = User.find_by_mobile(@admin_cargo.mobile)
   

    if( @current_cargo.company.company_type == "company")
      if  @current_cargo.company.company_information.present?
        @edit = true
        @info =  @current_cargo.company.company_information
      else
        @info =  @current_cargo.company.build_company_information
      end
    else
      redirect_to root_path , notice: "Invalid Request"
    end
    render :get_company_information

  end
  
  def add_cargo_company_information
    set_attachment_params
   @current_cargo = User.find params[:company_information][:userid]
   country_id = @current_cargo.country_id


    company = @current_cargo.company
    if company.company_information.present?
      initial_mobile_number = params[:company_information][:secondary_mobile_no_1]
      params[:company_information][:secondary_mobile_no_1] = make_secondary_phone_number country_id , params[:company_information][:secondary_mobile_no_1]
      initial_mobile_number1 = params[:company_information][:secondary_mobile_no]
      params[:company_information][:secondary_mobile_no] = make_secondary_phone_number country_id , params[:company_information][:secondary_mobile_no_1]
     
      
      company.company_information.update(company_params)
      flash[:notice] = "Your Profile information is updated Successfully."  
      info = company.company_information
    else
      initial_mobile_number = params[:company_information][:secondary_mobile_no_1]
      params[:company_information][:company_information] = make_secondary_phone_number country_id , params[:company_information][:secondary_mobile_no_1]
      initial_mobile_number1 = params[:company_information][:secondary_mobile_no]
      params[:company_information][:secondary_mobile_no] = make_secondary_phone_number country_id , params[:company_information][:secondary_mobile_no_1]
     

      info = company.build_company_information(company_params)
    end
    @current_user.company.update!(tax_registration_no: params[:company][:tax_registration_no]) if current_user.cargo_owner? and params[:company][:tax_registration_no].present?
    info.save
    @current_cargo.company.update!(blacklisted: false)
    
    redirect_to moderator_cargo_owners_path , notice: "Cargo created successfully!"
  end

  def set_user
    @user = User.find(params[:id])
  end
  def company_params
    params.require(:company_information).permit(:name ,:industry ,:license_number, :license_expiry_date,:website_address,:address,:trade_registration_no,:trade_registration_expiry,:contact1_first_name,:contact1_last_name,:contact1_mobile,:contact1_email,:contact1_designation,:contact1_office_no,:contact2_first_name,:contact2_last_name,:contact2_mobile,:contact2_email,:contact2_designation,:contact2_office_no,:contact3_first_name,:contact3_last_name,:contact3_mobile,:contact3_email,:contact3_designation,:contact3_office_no,:avatar,documents: [])
  end

  private

  def set_users_link
    @users_link= "active"
  end

  def admin_cargo_params
    params.require(:user).permit(:first_name, :last_name , :email, :mobile, :country_id ,:password)
  end

  def set_attachment_params
    if params[:company_information].present?
      begin
        params[:company_information][:avatar] = eval(params[:company_information][:avatar]).first if params[:company_information][:avatar].present?
      rescue SyntaxError => e
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      begin
          params[:company_information][:documents] = eval(params[:company_information][:documents].first) if params[:company_information][:documents].present?
      rescue SyntaxError => e
        params[:company_information][:documents] = params[:company_information][:documents].first.split(" ") rescue ""
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      params[:company_information][:documents] = params[:company_information][:documents].blank? ? [] : params[:company_information][:documents]
    elsif params[:company_information].present?
      begin
        params[:company_information][:avatar] = eval(params[:company_information][:avatar]).first if params[:company_information][:avatar].present?
      rescue SyntaxError => e
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      begin
        params[:company_information][:documents] = eval(params[:company_information][:documents].first) if params[:company_information][:documents].present?
      rescue SyntaxError => e
        params[:company_information][:documents] = params[:company_information][:documents].first.split(" ") rescue ""
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      params[:company_information][:documents] = params[:company_information][:documents].blank? ? [] : params[:company_information][:documents]
    end
  end


end

app/controllers/moderator/fleet_invoices_controller.rb
class Moderator::FleetInvoicesController < ModeratorController
  before_action :set_shipment , only: [:show]
  

  def show
    @name = "Advance Payment Receipt - VOC" +  Time.current.year.to_s + '%04d' % @shipment.id.to_s

    respond_to do |f|
      f.html
      f.js
      f.pdf do
        @pdf_view = true
        render pdf:  @name,
           template: "/moderator/fleet_invoices/pdf.html.erb",
           :encoding => "utf8",
           layout: "pdf.html.erb"
      end
    end
  end
  private
  def set_shipment
    
    puts"in the meantime"
    puts "\n\n\n\t\t #{params} \n\n"  
  
    @shipment = Shipment.find(params[:id])
    @fleet = User.find_by_id(params[:fleet_indi])
    @shipment_fleets = ShipmentFleet.all.where(shipment_id: @shipment.id ).order(:id)

    @category = params[:category]


    @cargo = User.find_by_company_id(@shipment.company_id) 
    
  end
end

app/controllers/moderator/invoices_controller.rb
class Moderator::InvoicesController < ModeratorController
	before_action :set_shipment , only: [:show]
  def show
    respond_to do |f|
      f.html
      f.js
      f.pdf do
        @pdf_view = true
        render pdf: "Invoice",
           template: "/moderator/invoices/pdf.html.erb",
           :encoding => "utf8",
           layout: "pdf.html.erb"
      end
    end
  end
  private
  def set_shipment
    @shipment = Shipment.find(params[:id])
  end
end

app/controllers/moderator/onlinedrivers_controller.rb
class Moderator::OnlinedriversController < ModeratorController
  
  before_action :check_if_moderator
  layout 'moderator'

  def index
    country = ISO3166::Country.find_country_by_name(current_user.country.name) rescue ""
    @user_country_coordinates = {lat: country.latitude , lng: country.longitude}
  	@vehicles = Vehicle.all
  end
end

app/views/moderator/shipment_dashboard/_completed.html.erb
  
<div class = "table-responsive1">
              <table class="table table-bordered table-striped " data-page-length='50' style="width: auto!important;">
                

 <thead  >
                <tr>
                  <%
                    columns = ["id","Customer","No. of Trucks","Pickup Location","Drop Location","Pickup Date","Pickup Time","Status","Actions"]
                     columns.each do |col|
                  %>
                    <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>    <tbody>
    <tbody  >
                <% shipments.each do |shipment|%>
                  <tr>
                    <td> <%= shipment.try(:id) %> </td>
                     <td> <%= shipment.try(:company).try(:company_name) %></td>
                     <td> <%= shipment.try(:no_of_vehicles) %></td>


                    <td> <%= shipment.try(:pickup_full_address) %> </td>
                    <td> <%= shipment.try(:drop_full_address) %> </td>
                    <td> <%= shipment.try(:pickup_date).strftime(display_date_format) %> </td>
                    <td> <%= local_time_format shipment.try(:pickup_time) %> </td>
                    <td> <%= shipment.status %></td>

                    <td>
                      <%= link_to "View", moderator_shipment_path(shipment), class: "btn btn-info btn-flat grid-btn" %>
                      <%= link_to "Edit", edit_moderator_shipment_path(shipment), class: "btn btn-warning btn-flat grid-btn" %>
                     <%= link_to fa_icon('eye'), edit_history_moderator_shipment_path(shipment.id), class: "btn btn-warning btn-flat grid-btn" %>

                      <% if shipment.completed? or shipment.cancel? %>
                        <%= link_to "Add Discount", edit_moderator_shipment_path(shipment) , class: "btn btn-success btn-flat grid-btn" , remote: true%>
                      <% end %>
                      <% if  shipment.state != "cancel"  && shipment.state != "completed" %>
                        <%= link_to "Cancel", cancel_moderator_shipment_path(shipment),method: :delete,data: { confirm: 'Are you sure?' }  ,class: "btn btn-danger btn-flat grid-btn" %>
                      <% end %>
                      
                      <% if [ "accepted","vehicle_assigned","ongoing"].include? shipment.state %>

                          <%= link_to "Complete ", moderator_shipment_path(shipment , "shipment[state_event]" => :completed, "shipment[completed_by]" => "admin"),method: :patch, data: {confirm: "Are you sure you want to complete this shipment?"}, class: "btn btn-danger btn-flat grid-btn" %>
                      <%end%>
                          <% link_text = shipment.shipment_fleets.present? ? "Change Driver" : "Assign Driver"%>
                           <%= link_to link_text ,assign_vehicle_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn"  %>         
                                                             <% if ["accepted", "vehicle_assigned", "ongoing","completed"].include? shipment.state %>

                          <% link_text = shipment.lorryz_share_amount.blank? ? "Add Costing" : "Update Costing"%>
                           <%= link_to link_text ,assign_cost_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn" , style: ' background-color: green; border:none' %>         
                      <%end%>
                      
              
                    </td>

           
                  </tr>
                <%end%>
                </tbody>
      
       
       
  </table>
</div>





  
    

app/views/moderator/shipment_dashboard/_ongoing.html.erb
  
<div class = "table-responsive1">
              <table class="table table-bordered table-striped " data-page-length='50' style="width: auto!important;">
                

 <thead  >
                <tr>
                  <%
                    columns = ["id","Customer","No. of Trucks","Pickup Location","Drop Location","Pickup Date","Pickup Time","Status","Actions"]
                     columns.each do |col|
                  %>
                    <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>    <tbody>
    <tbody  >
                <% shipments.each do |shipment|%>
                  <tr>
                    <td> <%= shipment.try(:id) %> </td>
                     <td> <%= shipment.try(:company).try(:company_name) %></td>
                     <td> <%= shipment.try(:no_of_vehicles) %></td>


                    <td> <%= shipment.try(:pickup_full_address) %> </td>
                    <td> <%= shipment.try(:drop_full_address) %> </td>
                    <td> <%= shipment.try(:pickup_date).strftime(display_date_format) %> </td>
                    <td> <%= local_time_format shipment.try(:pickup_time) %> </td>
                    <td> <%= shipment.status %></td>

                    <td>
                      <%= link_to "View", moderator_shipment_path(shipment), class: "btn btn-info btn-flat grid-btn" %>
                      <%= link_to "Edit", edit_moderator_shipment_path(shipment), class: "btn btn-warning btn-flat grid-btn" %>
                     <%= link_to fa_icon('eye'), edit_history_moderator_shipment_path(shipment.id), class: "btn btn-warning btn-flat grid-btn" %>

                      <% if shipment.completed? or shipment.cancel? %>
                        <%= link_to "Add Discount", edit_moderator_shipment_path(shipment) , class: "btn btn-success btn-flat grid-btn" , remote: true%>
                      <% end %>
                      <% if  shipment.state != "cancel"  && shipment.state != "completed" %>
                        <%= link_to "Cancel", cancel_moderator_shipment_path(shipment),method: :delete,data: { confirm: 'Are you sure?' }  ,class: "btn btn-danger btn-flat grid-btn" %>
                      <% end %>
                      
                      <% if [ "accepted","vehicle_assigned","ongoing"].include? shipment.state %>

                          <%= link_to "Complete ", moderator_shipment_path(shipment , "shipment[state_event]" => :completed, "shipment[completed_by]" => "admin"),method: :patch, data: {confirm: "Are you sure you want to complete this shipment?"}, class: "btn btn-danger btn-flat grid-btn" %>
                      <%end%>
                          <% link_text = shipment.shipment_fleets.present? ? "Change Driver" : "Assign Driver"%>
                           <%= link_to link_text ,assign_vehicle_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn"  %>         
                                                             <% if ["accepted", "vehicle_assigned", "ongoing","completed"].include? shipment.state %>

                          <% link_text = shipment.lorryz_share_amount.blank? ? "Add Costing" : "Update Costing"%>
                           <%= link_to link_text ,assign_cost_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn" , style: ' background-color: green; border:none' %>         
                      <%end%>
                      
              
                    </td>

           
                  </tr>
                <%end%>
                </tbody>
      
       
       
  </table>
</div>





  
    

app/views/moderator/shipment_dashboard/_posted.html.erb
     
<div class = "table-responsive1">
              <table class="table table-bordered table-striped " data-page-length='50' style="width: auto!important;">
                

 <thead  >
                <tr>
                  <%
                    columns = ["id","Customer","No. of Trucks","Pickup Location","Drop Location","Pickup Date","Pickup Time","Status","Actions"]
                     columns.each do |col|
                  %>
                    <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>    <tbody>
    <tbody  >
                <% shipments.each do |shipment|%>
                  <tr>
                    <td> <%= shipment.try(:id) %> </td>
                     <td> <%= shipment.try(:company).try(:company_name) %></td>
                     <td> <%= shipment.try(:no_of_vehicles) %></td>


                    <td> <%= shipment.try(:pickup_full_address) %> </td>
                    <td> <%= shipment.try(:drop_full_address) %> </td>
                    <td> <%= shipment.try(:pickup_date).strftime(display_date_format) %> </td>
                    <td> <%= local_time_format shipment.try(:pickup_time) %> </td>
                    <td> <%= shipment.status %></td>

                    <td>
                      <%= link_to "View", moderator_shipment_path(shipment), class: "btn btn-info btn-flat grid-btn" %>
                      <%= link_to "Edit", edit_moderator_shipment_path(shipment), class: "btn btn-warning btn-flat grid-btn" %>
                     <%= link_to fa_icon('eye'), edit_history_moderator_shipment_path(shipment.id), class: "btn btn-warning btn-flat grid-btn" %>

                      <% if shipment.completed? or shipment.cancel? %>
                        <%= link_to "Add Discount", edit_moderator_shipment_path(shipment) , class: "btn btn-success btn-flat grid-btn" , remote: true%>
                      <% end %>
                      <% if  shipment.state != "cancel"  && shipment.state != "completed" %>
                        <%= link_to "Cancel", cancel_moderator_shipment_path(shipment),method: :delete,data: { confirm: 'Are you sure?' }  ,class: "btn btn-danger btn-flat grid-btn" %>
                      <% end %>
                      
                      <% if [ "accepted","vehicle_assigned","ongoing"].include? shipment.state %>

                          <%= link_to "Complete ", moderator_shipment_path(shipment , "shipment[state_event]" => :completed, "shipment[completed_by]" => "admin"),method: :patch, data: {confirm: "Are you sure you want to complete this shipment?"}, class: "btn btn-danger btn-flat grid-btn" %>
                      <%end%>
                          <% link_text = shipment.shipment_fleets.present? ? "Change Driver" : "Assign Driver"%>
                           <%= link_to link_text ,assign_vehicle_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn"  %>         
                                                             <% if ["accepted", "vehicle_assigned", "ongoing","completed"].include? shipment.state %>

                          <% link_text = shipment.lorryz_share_amount.blank? ? "Add Costing" : "Update Costing"%>
                           <%= link_to link_text ,assign_cost_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn" , style: ' background-color: green; border:none' %>         
                      <%end%>
                      
              
                    </td>

           
                  </tr>
                <%end%>
                </tbody>
      
       
       
  </table>
</div>





  
    

app/views/moderator/shipment_dashboard/cargo_contracts.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row1">
        <div class="card-body">
          <div class = "card">
            <div class = "card-header">
              <h3 class="card-title">Cargo Contracts</h3>
            </div>
            <div class = "card-body">
              <table class="table table-bordered table-striped admin_listings" data-page-length='10'>
                <thead>
                <tr>
                  <% columns = ["pickup_location", "drop_location", "rate", "country_id", "Actions"]
                     columns.each do |col|
                  %>
                  <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>
                <tbody>
                <% @locations.each do |location|%>
                  <tr>
                    <td><%= location.try(:pickup_location) %></td>
                    <td><%= location.try(:drop_location) %></td>
                    <td><%= location.try(:rate) %></td>
                    <td><%= location.try(:country).try(:name).try(:humanize) %></td>
                    <td>
                      <%= link_to "Edit", edit_moderator_location_path(location), class: "btn btn-info btn-flat" %>
                    </td>
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/moderator/shipment_dashboard/fleet_owners.html.erb
<%= render partial: "user_details" , locals: {user_type: "Fleet" , users: @fleet_owners}%>