config/routes.rb
Rails.application.routes.draw do

  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]

  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up

     
    end
    # devise_scope :admin do
    #   get '/sign_up' => "/admin/fleet_individual/new", as: :sign_up
    # end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing

    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
  
     post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
     post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information

     post "/shipments/add_admin_shipment_details" => "shipments#add_admin_shipment_details", as: :add_admin_shipment_details
  
     get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

     resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :primary_vehicle

    resources :pages
    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
    end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :preferred_location , except: [:destroy]
    resources :vehicle_types, except: [:destroy]

    resources :blogs, except: [:destroy]
    resources :locations
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]

    resources :change_destination_requests
    resources :vendor, except: [:destroy]
    resources :shipments do
      collection do
      get :cargo_invoice
      put :presign_upload

      end
      member do
        delete :cancel
        get :assign_vehicle
        get :assign_cost
        get :email
        get :edit_history

        patch :status_email





      end
      collection do
        post :get_bulk_coordinates

      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do
      collection do
        post :get_all_drivers
        post :get_all_drivers_filtered
        get :change_password


      end
    end


    resources :payments
  end

  namespace :moderator do
    root 'dashboard#index'
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing

    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
    post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
    post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

    resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :vendor, except: [:destroy]
      resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
      end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]
    resources :dashboard , only: [:index]
    resources :preferred_location , except: [:destroy]

    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :payments
    resources :shipments do
      collection do
        get :cargo_invoice
        put :presign_upload

        end

      member do
        delete :cancel
        get :assign_vehicle
        get :assign_cost
         get :email
         patch :status_email
         get :edit_history
      end
      
      collection do
        post :get_bulk_coordinates
      end
    end
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do

app/controllers/api/v1/cargo/shipments_controller.rb
class Api::V1::Cargo::ShipmentsController < Api::V1::ApiController

  before_action :verify_jwt_token
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
    render json: @shipments, status: :ok
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.create shipment_params
    puts @shipment.errors.full_messages
    ShipmentMailer.new_shipment( @shipment.id ).deliver_now if  @shipment.errors.blank?

    @shipment.errors.blank? ? ( render "create" , status: :ok ) : (render json: { errors: @shipment.errors.full_messages }, status: :bad_request)
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    if @shipment.update(shipment_params)
			@shipment.bids.destroy_all
			@shipment.update_attributes(is_expired: "false")
      if @shipment.state == "posted"
        @shipment.shipment_posted_notifications
      end
      render json: {update: true, status: :ok}
    else
      puts @shipment.errors.full_messages
      render json: { errors:  @shipment.errors.full_messages }, status: :bad_request
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def calculate_fare
    @shipment = Shipment.new shipment_params
    fare = @shipment.prorate_formula
    distance = @shipment.distance_between_start_and_end_point
    render json: {fare: fare, distance: distance}, status: :ok
  end

  def posted
    @shipments = Shipment.where(company_id: params[:company_id]).posted.page params[:page]
  end

  def ongoing
    @shipments = Shipment.where(company_id: params[:company_id]).ongoing.page params[:page]
  end

  def upcoming
    @shipments = Shipment.where(company_id: params[:company_id].to_i, state: ["accepted", "vehicle_assigned"]).page params[:page]
  end


  def completed
    @shipments = Shipment.where(company_id: params[:company_id].to_i).where('state =? OR (state=? AND cancel_by=?)', "completed",'cancel','cargo_owner').page params[:page]

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:pickup_building_name, :drop_building_name, :amount_per_vehicle, :cancel_reason, :cancel_by, :state_event,:payment_option, :state, :id,:company_id, :country_id, :pickup_location, :pickup_date, :pickup_time, :loading_time, :drop_location, :unloading_time, :expected_drop_off, :vehicle_type_id, :no_of_vehicles, :cargo_description, :cargo_packing_type, :pickup_lat, :pickup_lng, :drop_lat, :drop_lng, :drop_city, :pickup_city, :location_id, :amount, :is_pickup_now)
    end
end

app/controllers/moderator/fleet_invoices_controller.rb
class Moderator::FleetInvoicesController < ModeratorController
  before_action :set_shipment , only: [:show]
  

  def show
    @name = "Advance Payment Receipt - VOC" +  Time.current.year.to_s + '%04d' % @shipment.id.to_s

    respond_to do |f|
      f.html
      f.js
      f.pdf do
        @pdf_view = true
        render pdf:  @name,
           template: "/moderator/fleet_invoices/pdf.html.erb",
           :encoding => "utf8",
           layout: "pdf.html.erb"
      end
    end
  end
  private
  def set_shipment
    
    puts"in the meantime"
    puts "\n\n\n\t\t #{params} \n\n"  
  
    @shipment = Shipment.find(params[:id])
    @fleet = User.find_by_id(params[:fleet_indi])
    @shipment_fleets = ShipmentFleet.all.where(shipment_id: @shipment.id ).order(:id)

    @category = params[:category]


    @cargo = User.find_by_company_id(@shipment.company_id) 
    
  end
end

app/controllers/moderator/gps_vehicle_controller.rb
class Moderator::GpsVehicleController < ModeratorController
  before_action :authenticate_user!
  before_action :check_if_moderator
  before_action :set_country , only: [:edit, :create,:index , :new,  :update, :destroy]
  before_action :set_gps , only: [:edit,  :update, :destroy]

  before_action :set_vehicle_driver, only: [:edit , :new, :create , :update]
  before_action :set_gps_link ,only: [:edit,  :index , :new]
  layout 'moderator'
  def index
    params[:query] ||=   {}
    params[:query][:country_id]=current_user.country.try(:id)
    @gps = GpsVehicle.search(params[:query])
    @total = GpsVehicle.where(:country_id => current_user.country.try(:id)).count
    @active_gps = Vehicle.vehicle_owners.fleet_gps_owners_country(current_user.country.try(:id)).count + Vehicle.vehicle_owners.fleet_admin_gps_owners_country(current_user.country.try(:id)).count
    @inactive_gps =@total -  @active_gps
    @active_fleet = User.busy_fleet_owners.individual_fleet_owners 
    @active_fleet_admin = User.busy_fleet_individual_owners.individual_fleet_owners 

    @active_fleets =   @active_fleet.select(:company_id)
    @active_fleet_admins =@active_fleet_admin.select(:company_id)

    @total = "Total GPS: " +@total.to_s
    @active_gps = "Busy GPS: "+ @active_gps.to_s
    @inactive_gps = "Free GPS:" +@inactive_gps.to_s

    
    respond_to do |format|
      format.html
      format.xlsx {
        render xlsx: 'xlsx_GPS', filename: "all_gps.xlsx", disposition: 'attachment'
      }
    end
  end
  def new
    @moderator_gps = GpsVehicle.new
  end
  def create
    set_gps_params
    @moderator_gps = GpsVehicle.new(gps_params)
    if @moderator_gps.save
      redirect_to moderator_gps_vehicle_index_path , notice: "GPS created successfully!"
    else
      render :new
    end
  end
  def edit
  end
  def update
    set_gps_params
    if @moderator_gps.update(gps_edit_params)
      redirect_to moderator_gps_vehicle_index_path , notice: "Country updated successfully!"
    else
      render :edit
    end
  end
  def destroy
    if @admin_country.destroy
      redirect_to admin_countries_path , notice: "Country destroyed successfully"
    else
      redirect_back(fallback_location: admin_countries_path)
    end
  end
  private
  def gps_params
     if params[:gps_vehicle][:vehicle_id].present?
     @user = User.find_by_id params[:gps_vehicle][:vehicle_id]
     @vehicle =@user.vehicle
     params[:gps_vehicle][:vehicle_id] =@vehicle.id
    else
      params[:gps_vehicle][:vehicle_id] = ''
     end

     params.require(:gps_vehicle).permit(:imei, :supplier,:manufacturer ,:country_id, :vehicle_id, :status)
  end
  def gps_edit_params

    if params[:gps_vehicle][:vehicle_id].present?
    @user = User.find_by_id params[:gps_vehicle][:vehicle_id]
    @vehicle =@user.vehicle
     params[:gps_vehicle][:vehicle_id] =@vehicle.id
    else
      params[:gps_vehicle][:vehicle_id] = ''
     end
    params.require(:gps_vehicle).permit(:vehicle_id, :status)
 end
  def set_country
    @countries = Country.all.where(:id => current_user.country.try(:id))
  end
  def set_gps_link
    @gps_link = "active"
  end
  

  def set_gps
    @moderator_gps = GpsVehicle.find(params[:id])
  end

  def set_gps_params
    id = params[:gps_vehicle][:id]
  end

  def set_vehicle_driver
    @users = User.individual_fleet_owners.where(:country_id => current_user.country.try(:id))
  end

end

app/controllers/moderator/onlinedrivers_controller.rb
class Moderator::OnlinedriversController < ModeratorController
  
  before_action :check_if_moderator
  layout 'moderator'

  def index
    country = ISO3166::Country.find_country_by_name(current_user.country.name) rescue ""
    @user_country_coordinates = {lat: country.latitude , lng: country.longitude}
  	@vehicles = Vehicle.all
  end
end

app/views/moderator/shipments/_edit.html.erb
<div class="modal fade" id="discount_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Discount Value</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(@shipment, url: moderator_shipment_path(@shipment)) do |f| %>
        <div class="modal-body">
          <div class="container">
            <div class="form-group">
              <%= f.number_field :discount,class: "form-control",placeholder: "Discount Value",:required => true%>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/moderator/shipments/_form.html.erb
  <%# form_with(model: shipment, local: true) do |form| %>
<%=form_for @shipment, url: moderator_shipments_path do |f|%>
  <!--<% if cargo_shipment.errors.any? %>-->
    <!--<div id="error_explanation">-->
      <!--<h2><%= pluralize(cargo_shipment.errors.count, "error") %> prohibited this cargo_shipment from being saved:</h2>-->
<!---->
      <!--<ul>-->
      <!--<% cargo_shipment.errors.full_messages.each do |message| %>-->
        <!--<li><%= message %></li>-->
      <!--<% end %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--<% end %>-->
    <%= render partial: "form_fields" , locals: {f: f, action: action, submit_button_text: "Post Request"}%>
<% end %>

app/views/moderator/shipments/assign_cost.js.erb
$("#assign_cost_modal").html("<%= escape_javascript(render 'assign_cost') %>");
$("#assign_cost_modal").modal('show')

app/views/moderator/shipments/index.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row1">
        <div class="card-body">
          <div class = "card">
            <div class = "card-header">
              <h3 class="card-title">Shipments</h3>
              <div class = "row">
                <div class  =" col-md-4"></div>
                <div class  =" col-md-3">
                  <%# <%= text_field_tag :start_date, nil, class: "search-datepicker datepick form-control" ,placeholder:  "Start Date"  %>
                </div>
                <div class  =" col-md-3">
                  <%# <%= text_field_tag :end_date ,nil, class: "search-datepicker datepick form-control" ,placeholder:  "End Date"  %> 
                </div>
                <%# <%= link_to "Download in Excel" , moderator_shipments_path(format: :xlsx) , id: "shipment_xlsx" ,class: "btn btn-flat btn-success pull-right" , onclick: "append_date_range_params(this);"%> 
               <br>
                <%= link_to "Add New Shipment" ,new_moderator_shipment_path , id: "shipment_xlsx" ,class: "btn btn-flat btn-success pull-right" %>

              </div>
           
            </div>
            <div class = "card-body">
              <div class="search shipment_form">
                <a href="clear()" class="clear_filter hide"> Clear</a>
                <%= form_for "query", url:moderator_shipments_path, method: :get do |f|%>
                <div class="row ship">
                  <div class="col-md-4 col-sm-4 ">
                   <%= f.label :cargo_owner %>
                   <div class="selectHolder">
                      <%= f.select :cargo_owner, User.cargo_owners.collect {|p| [ p.first_name, p.try(:company).try(:id) ] }, {include_blank: true, :selected => params[:query][:cargo_owner]  }, {:class => "form-control "} if  params[:query][:cargo_owner].present? && params[:query][:cargo_owner]  != ""%>
                     <%= f.select :cargo_owner, User.cargo_owners.collect {|p| [ p.first_name, p.try(:company).try(:id) ] }, {include_blank: true  }, {:class => "form-control "}  if  params[:query][:cargo_owner].blank? || params[:query][:cargo_owner]  == "" %>
                   </div>

                  </div>
                  <div class="col-md-4 col-sm-4 ">
                   <%= f.label :fleet_owner %>
                    <div class="selectHolder">
                      <%= f.select :fleet_owner,  User.fleet_owners.collect {|p| [ p.first_name, p.try(:company).try(:id) ] }, {include_blank: true, :selected => params[:query][:fleet_owner] }, {:class => "form-control"} if  params[:query][:fleet_owner].present? && params[:query][:fleet_owner]  != ""%>
                      <%= f.select :fleet_owner,  User.fleet_owners.collect {|p| [ p.first_name, p.try(:company).try(:id) ] }, {include_blank: true}, {:class => "form-control"}  if  params[:query][:fleet_owner].blank? || params[:query][:fleet_owner]  == ""%>
                    </div>

                  </div>
                  <div class="col-md-4 col-sm-4  pad-2">
                    <%= f.label :country_id , "Country" %>
                    <div class="selectHolder">
                      <%= f.collection_select :country_id ,Country.where(:id => current_user.country.try(:id)), :id,:name,{include_blank: true, :selected => params[:query][:country_id] },{class: "form-control" } %>
                    </div>

                  </div>

                  <div class="col-md-4 col-sm-4 pad-2">
                    <%= f.label :status %>
                    <div class="selectHolder">
                      <%= f.select :status,shipment_states, {include_blank: true, :selected => params[:query][:status] }, {:class => "form-control"}  %>
                     </div>  </div>

                      <div class="col-md-4 col-sm-4 pad-2">
                    <%= f.label :shipment_no %>
                    <div class="selectHolder">
                   <%= f.collection_select :shipment_no, Shipment.where(:country_id => current_user.country.try(:id)).order(id: :asc) , :id,:id,{include_blank: "Specify Shipment number?", :selected => params[:query][:shipment_no]}, onchange: "populate_data()" %>
               
                    </div>

                  </div>
                  <div class="col-md-4 col-sm-4 pad-2">
                    <%= f.label :pickup_date %>
                    <div class="selectHolder">
                      <%= f.text_field :pickup_date,value: params[:query][:pickup_date] , class: "search-datepicker datepick form-control" ,placeholder:  "Pickup Date"  %>
                    </div>

                  </div>
                  <div class="col-md-4 col-sm-4">
                    <%= f.submit "Search" , class: "btn btn-primary submit-btn" %>
                  </div>
                </div>
                <% end %>
              </div>

              <table class="table table-bordered table-striped admin_listings" data-page-length='50' style="width: auto!important;">
                <thead>
                <tr>
                  <%
                    columns = ["id","Customer","No. of Trucks","Pickup Location","Drop Location","Pickup Date","Pickup Time","Status","Actions"]
                     columns.each do |col|
                  %>
                    <th><%= col.humanize %></th>
                  <%end%>
                </tr>
                </thead>
                <tbody>
                <% @shipments.each do |shipment|%>
                  <tr>
                  
                    <td> <%= shipment.try(:id) %> </td>
                                        <td> <%= shipment.try(:company).try(:company_name) %></td>
                          <td> <%= shipment.try(:no_of_vehicles) %></td>

                    <td> <%= shipment.try(:pickup_full_address) %> </td>
                    <td> <%= shipment.try(:drop_full_address) %> </td>
                    <td> <%= shipment.try(:pickup_date).strftime(display_date_format) %> </td>
                    <td> <%= local_time_format shipment.try(:pickup_time) %> </td>
                     <td> <%= shipment.status %></td>
                    <td>
                      <%= link_to "View", moderator_shipment_path(shipment), class: "btn btn-info btn-flat grid-btn" %>
                      <%= link_to "Edit", edit_moderator_shipment_path(shipment), class: "btn btn-warning btn-flat grid-btn" %>
                                       <%= link_to fa_icon('eye'), edit_history_moderator_shipment_path(shipment.id), class: "btn btn-warning btn-flat grid-btn" %>

                      <% if shipment.completed? or shipment.cancel? %>
                        <%= link_to "Add Discount", edit_moderator_shipment_path(shipment) , class: "btn btn-success btn-flat grid-btn" , remote: true%>
                      <% end %>
                      <% if  shipment.state != "cancel"  && shipment.state != "completed" %>
                        <%= link_to "Cancel", cancel_moderator_shipment_path(shipment),method: :delete,data: { confirm: 'Are you sure?' }  ,class: "btn btn-danger btn-flat grid-btn" %>
                      <% end %>
                        <% if [ "accepted","vehicle_assigned","ongoing"].include? shipment.state  %>
                          <%= link_to "Complete ", moderator_shipment_path(shipment , "shipment[state_event]" => :completed, "shipment[completed_by]" => "admin"),method: :patch, data: {confirm: "Are you sure you want to complete this shipment?"}, class: "btn btn-danger btn-flat grid-btn" %>
                      <%end%>
                           <% if ["accepted", "vehicle_assigned", "ongoing","posted"].include? shipment.state %>
                          <% link_text = shipment.shipment_fleets.present? ? "Change Driver" : "Assign Driver"%>
                           <%= link_to link_text ,assign_vehicle_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn"  %>         
                      <%end%>
                                       <% if ["accepted", "vehicle_assigned", "ongoing","completed"].include? shipment.state %>
                          <% link_text = shipment.lorryz_share_amount.blank? ? "Add Costing" : "Update Costing"%>
                           <%= link_to link_text ,assign_cost_moderator_shipment_path(shipment.id),remote: :true, class: "btn btn-danger btn-flat grid-btn" , style: ' background-color: green; border:none' %>         
                      <%end%>
                    
                    </td>

           
                  </tr>
                <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>